server:
  port: 8044
spring:
  redis:
    ## redis集群环境
    #    cluster:
    #      nodes: 127.0.0.1:6379
    #      max-redirects: 10 #跨群集执行命令时要遵循的最大重定向数
    ## 单节点环境
    host: 127.0.0.1
    port: 6379